name: 'Push Docs'
description: 'Push docs to repository'
inputs:
  target_repository:
    description: 'Target repository'
    required: true
  pat_token:
    description: 'Personal Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup-python-docs-action
      with:
        python-version: "3.11"

    - name: Copy docs to docs_repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.target_repository }}
        token: ${{ inputs.pat_token }}
        path: docs_repo
        ref: main

    - name: Create repo subdirectory
      run: |
        REPO_SUBDIR="projects/${{ github.repository }}"
        mkdir -p "docs_repo/docs/$REPO_SUBDIR/docs/"
      shell: bash

    - name: Move docs
      run: |
        REPO_SUBDIR="projects/${{ github.repository }}"
        cp -r docs/* "docs_repo/docs/$REPO_SUBDIR/docs/"
        cp -r mkdocs.yml "docs_repo/docs/$REPO_SUBDIR/"
      shell: bash

    - name: Update index.md
      run: |
        REPO_SUBDIR="projects/${{ github.repository }}/site"
        echo "- [${{ github.repository }}]($REPO_SUBDIR)" >> docs_repo/docs/index.md
      shell: bash

    - name: Commit and push
      run: |
        cd docs_repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag docs-updated-${{ github.run_id }}
        git push origin docs-updated-${{ github.run_id }}
        git add .
        REPO_SUBDIR="docs/projects/${{ github.repository }}/mkdocs.yml"
        git commit -m "$REPO_SUBDIR" -a
        git push origin main
      shell: bash
